# Generated by Django 4.2.2 on 2023-07-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_images', models.ImageField(default='Project Images', upload_to=None)),
                ('project_body', models.TextField(blank=True, null=True)),
                ('project_links', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='testModel',
        ),
    ]
