# Generated by Django 4.2.2 on 2023-07-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_projectmodel_project_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogposts',
            old_name='post_body',
            new_name='blog_body',
        ),
        migrations.RenameField(
            model_name='blogposts',
            old_name='created_date',
            new_name='blog_created_date',
        ),
        migrations.RenameField(
            model_name='blogposts',
            old_name='title',
            new_name='blog_title',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project_images',
            new_name='project_image',
        ),
        migrations.AddField(
            model_name='blogposts',
            name='blog_image',
            field=models.ImageField(default='Project Images', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='blog_image_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='blog_image_info_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='blog_image_info_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='blog_image_three',
            field=models.ImageField(default='Project Images', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='blog_image_two',
            field=models.ImageField(default='Project Images', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='image_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='image_info_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='image_info_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='project_image_three',
            field=models.ImageField(default='Project Images', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='project_image_two',
            field=models.ImageField(default='Project Images', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_links',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
